# Generated by Django 6.1 on 2026-08-11 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BatchUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_file", models.FileField(upload_to="batches/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AudioAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="audio_clips/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_details", models.TextField(blank=True, default="")),
                (
                    "emotional_tone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("neutral", "Neutral"),
                            ("satisfied", "Satisfied"),
                            ("frustrated", "Frustrated"),
                            ("upset", "Upset"),
                            ("distressed", "Distressed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "emotional_intensity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("background_noise_present", models.BooleanField(default=False)),
                (
                    "background_noise_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "background_noise_severity",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "audio_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clear", "Clear"),
                            ("slightly_impaired", "Slightly Impaired"),
                            ("severely_impaired", "Severely Impaired"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("speaker_overlap_present", models.BooleanField(default=False)),
                ("long_silence_present", models.BooleanField(default=False)),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="audio_analytics.batchupload",
                    ),
                ),
            ],
        ),
    ]
