# Generated by Django 5.2.17 on 2026-08-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchupload",
            name="metrics_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
