# Generated by Django 5.2.17 on 2026-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_analytics", "0003_batchupload_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchupload",
            name="name",
            field=models.CharField(default="Live Recording", max_length=255),
        ),
    ]
