# Generated by Django 5.2.17 on 2026-08-16 14:51

import audio_analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_analytics", "0005_device_batchupload_device"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="api_token",
        ),
        migrations.AddField(
            model_name="device",
            name="key",
            field=models.CharField(
                default=audio_analytics.models.generate_device_key,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
