# Generated by Django 5.2.17 on 2026-08-25 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audio_analytics", "0008_payment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="audio_analy_user_id_64d3b2_idx",
            old_name="audio_analy_payment_user_idx",
        ),
    ]
